#---
#- name: Display package update details
- hosts: 192.168.0.111
  gather_facts: true
  become: true

  tasks:
    - name: Get package updates
      command: yum check-update
      register: package_updates
      become: true
      ignore: yes

    - name: Display package update details
      debug:
        msg: "{{ package_updates.stdout_lines }}"
