#---
#- name: check browser version and update browser
- hosts: 192.168.29.115
  gather_facts: true
  become: true

  tasks:
    - name: check chrome version
      command: google-chrome-stable --version
      register: package_updates
      become: true

    - name: Display chrome version
      debug:
        msg: "{{ package_updates.stdout_lines }}"
        
    - name: check firefox version
      command: firefox --version
      register: package1_updates
      become: true
      
    - name: Display firefox version
      debug:
        msg: "{{ package1_updates.stdout_lines }}"
        
    - name: upgrade chrome to latest version
      command: yum upgrade google-chrome-stable
      become: true
      
    
    - name: upgrade firefox to latest version
      command: yum upgrade firefox
      become: true
