- hosts: 192.168.29.115
  gather_facts: true
  become: true

  tasks:
    - name: Clear Firefox credentials
      shell: "rm -rf ~/.mozilla/firefox/x7sglt2r.default-default/logins.json"
      shell: "rm -rf ~/.mozilla/firefox/x7sglt2r.default-default/logins-backup.json"
      shell: "rm -rf ~/.mozilla/firefox/x7sglt2r.default-default/key4.db"
