#---
#- name: Display package update details
- hosts: 192.168.0.111
  gather_facts: true

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: true

    - name: Get available package updates
      apt:
        upgrade: "dist"
        simulate: yes
      register: package_updates
      become: true

    - name: Display package update details
      debug:
        msg: "{{ package_updates.stdout_lines }}"
